# Generated by Django 5.0.6 on 2024-07-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='countriesSelected',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='getFoods.countries'),
        ),
    ]
