# Generated by Django 5.0.6 on 2024-07-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0004_rename_name_users_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='countryName',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='countriesSelected',
            new_name='countries_selected',
        ),
    ]
