# Generated by Django 5.0.6 on 2024-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0005_rename_countryname_countries_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='countries_not_selected',
            field=models.ManyToManyField(blank=True, related_name='non_visitors', to='getFoods.countries'),
        ),
    ]
