# Generated by Django 5.0.6 on 2024-07-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('getFoods', '0007_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
    ]
