# Generated by Django 5.0.6 on 2024-07-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0009_remove_users_countries_not_selected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='city_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='country_name',
            new_name='country',
        ),
    ]
