# Generated by Django 5.0.6 on 2024-07-24 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('getFoods', '0010_rename_city_name_destinations_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='destinations',
        ),
        migrations.DeleteModel(
            name='Destinations',
        ),
        migrations.AddField(
            model_name='users',
            name='destinations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
