# Generated by Django 5.0.6 on 2024-07-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0012_remove_users_destinations_userstemp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstemp',
            old_name='city',
            new_name='destinations',
        ),
    ]
