# Generated by Django 5.0.6 on 2024-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('getFoods', '0013_rename_city_userstemp_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='destinations',
            field=models.ManyToManyField(blank=True, null=True, to='cities_light.city'),
        ),
        migrations.DeleteModel(
            name='UsersTemp',
        ),
    ]
