# Generated by Django 5.0.6 on 2024-07-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0015_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_descr',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
    ]
