# Generated by Django 5.0.6 on 2024-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0016_rename_food_descr_food_descr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='resto_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='resto_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
