# Generated by Django 5.0.6 on 2024-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0018_remove_food_resto_link_food_resto_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='resto_location',
        ),
        migrations.AddField(
            model_name='food',
            name='resto_location_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='resto_location_y',
            field=models.IntegerField(null=True),
        ),
    ]
