# Generated by Django 5.0.6 on 2024-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0021_alter_food_resto_latitude_alter_food_resto_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='resto_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='resto_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
