# Generated by Django 5.0.6 on 2024-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getFoods', '0023_alter_food_resto_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='search_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='descr',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
