# Generated by Django 5.0.6 on 2024-08-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('getFoods', '0024_remove_food_name_food_display_name_food_search_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='resto_latitude',
        ),
        migrations.RemoveField(
            model_name='food',
            name='resto_longitude',
        ),
        migrations.RemoveField(
            model_name='food',
            name='resto_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resto_latitude', models.FloatField(blank=True, null=True)),
                ('resto_longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('food_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='getFoods.food')),
            ],
        ),
    ]
