# Generated by Django 4.2.15 on 2025-08-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('getFoods', '0025_remove_food_resto_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='cities_light.city'),
        ),
    ]
